server:
  port: 9090
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: Pass123
    url: jdbc:mysql://localhost:3306/sbms
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
